### ISSUE TITLE
!game for mods and group problem

### ISSUE THREAD

**Issue by EvilTaiga** [GloriousEggroll/PhantomBot#10]
hey, i change the data how u say, but my mod can`t change the !game or !title "Only a Caster has access to that command!", so i looked under inistore in the group.ini and everyone has a 2 behind the = and according to the groups.ini file means that, everyone is a mod.

**Comment by phantomindex** [comment]
!group set name Administrator.

The reason a mod can't use them is because only a Caster can. If you set the permission for !game and !title it only affects them when you use them without a string example: "!title" 

Trying to do "!title this is dragon quest" that sentence is a string. The permcom system doesn't let you change the permission for this version of the command.

So if you set a trusted moderator to administrator it should solve your problem.

**Comment by EvilTaiga** [comment]
I get the Error "Only a Caster has access to that command!" and I have another problem, i use the phrase if someone write the name of the bot, he say "Who will speak against me, get a timeout" and today I want add another phrase with "!addphrase Rock Let's Rock" but he accepts only the "Let's" and ignore Rock, I have exactly the same as done with the name :/

**Comment by phantomindex** [comment]
Could you type this better?  I have a hard time understanding what you're trying to tell me.

as for addphrase do this: !addphrase rock "Let's Rock"

**Comment by EvilTaiga** [comment]
It works now, the bot run on a linux server and I had to set the rights for the folder "initstore" to writable, but now I got that error:"ChannelUsersCache.updateCache>>Failed to update users: JSONObject["error"] not found." don't know what that means :/ 

An idea what's wrong if I type "!gane test" and the following error get? "Failed to change the status. TwitchAPI must be having issues"

Thanks in advance for all :)

**Comment by gmt2001** [comment]
If you enable the logs, it will put the actual error in the errorlog for the !game command

ChannelUsersCache error means that an error was returned when trying to pull the viewer list, but it could not determine an error message from Twitch
